name: Delete microservice

on:
  workflow_dispatch: 

jobs:
  delete:
    runs-on: ubuntu-latest 
    env:
      AZURE_RG: "tamimshahriarsit722part5"
      AZURE_AKS: "tamimshahriarsit722part5"

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: tale/kubectl-action@v1
        with:
          kubectl-version: v1.24.2
      
      - name: Delete
        run: ./scripts/delete.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ./scripts/terraform
        run: terraform init

      - name: Terraform Delete
        id: terraform
        working-directory: ./scripts/terraform
        run: terraform destroy -auto-approve