name: Deploy microservice

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest 
    env:
      VERSION: ${{ github.sha }}
      TF_VERSION: '1.0.0'  # Specify Terraform version
      AZURE_RG: "tamimshahriarsit722part5"
      AZURE_AKS: "tamimshahriarsit722part5"
      ACR_NAME: "tamimshahriarsit722part5"


    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./scripts/terraform
        run: terraform init

      - name: Terraform Apply
        id: terraform
        working-directory: ./scripts/terraform
        run: terraform apply -auto-approve
          # echo "::set-output name=acr_server::$(terraform output -raw acr_login_server)"
          # echo "::set-output name=acr_username::$(terraform output -raw acr_username)"
          # echo "::set-output name=acr_password::$(terraform output -raw acr_password)"

      - run: terraform output -raw acr_login_server 
        working-directory: ./scripts/terraform

      - name: checking the command
        run: |
          terraform output -raw acr_login_server
          terraform output -raw acr_username
          terraform output -raw acr_password
        working-directory: ./scripts/terraform

      - name: checking another command
        run: |
          terraform output -raw acr_login_server | awk -F '::' '{print $1}'
          terraform output -raw acr_username | awk -F '::' '{print $1}'
          terraform output -raw acr_password | awk -F '::' '{print $1}'
        working-directory: ./scripts/terraform

      - name: Retrieve Registry Info from Terraform Outputs
        id: tf
        working-directory: ./scripts/terraform
        run: |
          echo "ACR_NAME=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "ACR_UN=$(terraform output -raw acr_username)" >> $GITHUB_OUTPUT
          echo "ACR_PW=$(terraform output -raw acr_password)" >> $GITHUB_OUTPUT
             
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Build
        run: ./scripts/build-image.sh

      # - run: terraform output -raw acr_password | awk -F '::' '{print $1}' | docker login $ACR_NAME.azurecr.io --username $ACR_NAME --password-stdin
      #   working-directory: ./scripts/terraform

      - name: Publish
        env:
          CONTAINER_REGISTRY: ${{steps.tf.outputs.ACR_NAME}}
          REGISTRY_UN: ${{steps.tf.outputs.ACR_UN}}
          REGISTRY_PW: ${{steps.tf.outputs.ACR_PW}}
        run: ./scripts/push-image.sh

      - uses: tale/kubectl-action@v1
        with:
          kubectl-version: v1.24.2
    
      - name: Deploy
        run: ./scripts/deploy.sh

      # - name: Retrieve Registry Info from Terraform Outputs
      #   id: tf
      #   working-directory: ./scripts/terraform
      #   run: |
      #     echo "ACR_NAME=$(terraform output -raw acr_login_server | awk -F '::' '{print $1}')" >> $GITHUB_ENV
      #     echo "ACR_UN=$(terraform output -raw acr_username | awk -F '::' '{print $1}')" >> $GITHUB_ENV
      #     echo "ACR_PW=$(terraform output -raw acr_password | awk -F '::' '{print $1}')" >> $GITHUB_ENV